"""Static closure checks for the full-pool wagering replay adapter.

The scorer/data checks live in test_wager_replay_audit.py and the final-chain
preflight.  These tests prevent a future consumer from silently dropping the
verified overlay, or from leaking it into the fp16 sensitivity arm.
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


CONSUMERS = (
    "results/recompute_20260703/build_and_recompute.py",
    "results/recompute_20260703/step4_numbers.py",
    "results/recompute_20260703/step4b_numbers.py",
    "results/recompute_20260703/sensitivity.py",
    "results/twolevel_bootstrap_20260712/two_level_bootstrap.py",
    "results/construct_native_20260711/build_construct_matrix.py",
    "scripts/reanalysis/apply_corrected_results.py",
    "scripts/reanalysis/aplus_rescore_20260718.py",
    "paper/figures/generate_all.py",
)


def source(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def test_every_per_item_consumer_is_wager_overlay_aware() -> None:
    for relative in CONSUMERS:
        text = source(relative)
        assert "WAGER_OVERLAY" in text or "wager_overlay" in text, relative


def test_fp16_arm_is_explicitly_isolated() -> None:
    text = source("results/recompute_20260703/step4b_numbers.py")
    assert 's in ("full_eval_20260526_2208", "full_eval_expansion")' in text
    assert "full_eval_fp16" in text


def test_final_chain_hash_binds_replay_manifest_and_overlay() -> None:
    driver = source("scripts/reanalysis/run_final_chain.sh")
    postflight = source("scripts/reanalysis/chain_postflight.py")
    assert "WAGER_REPLAY_MANIFEST.json" in driver
    assert 'wman["outputs"].get(wrel)' in driver
    assert 'wman.get("execution", {}).get("git_head") == rev' in driver
    assert 'wager_construct_overlay_representable' in driver
    assert "wager_overlay_sha256" in postflight
    assert 'aplus["inputs"].get("sm_overlay"' in postflight
    assert 'aplus.get("outputs_sha256", {})' in postflight
    for filename in (
        "WAGER_REPLAY_MANIFEST.json",
        "wager_accuracy_overlay.json",
        "wager_replay_results.json",
        "wager_replay_items.csv",
    ):
        assert filename in postflight


def test_final_chain_refuses_login_node_execution() -> None:
    driver = source("scripts/reanalysis/run_final_chain.sh")
    assert "SLURM_JOB_ID" in driver
    assert 'c01*)' in driver
    assert "final_chain_source_manifest.py --verify" in driver
    assert "COGARENA_CHAIN_STARTED_NS" in driver
    postflight = source("scripts/reanalysis/chain_postflight.py")
    assert "TRUSTED_PRECHAIN_INPUTS" in postflight
    assert "were not regenerated by this chain" in postflight
